/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/Assembly_for_robotic_car.glb --transform 
Files: public/Assembly_for_robotic_car.glb [9.24MB] > C:\Users\yashv\sproutdevelopment\Portfolio\portfolio-app\Assembly_for_robotic_car-transformed.glb [574.2KB] (94%)
*/

import React from 'react'
import { useGLTF, OrthographicCamera } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Assembly_for_robotic_car-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <OrthographicCamera makeDefault={false} far={1.699} near={1.212} position={[-0.36, 1.649, 0.889]} rotation={[-2.134, -0.888, -2.016]} />
      <mesh geometry={nodes['Wheel_D65x25-3'].geometry} material={materials.PaletteMaterial001} position={[0.626, 0.914, 1.458]} />
      <mesh geometry={nodes['MotorDCTT-1'].geometry} material={materials.PaletteMaterial002} position={[0.78, 0.915, 1.419]} rotation={[0, 0, Math.PI / 2]} />
    </group>
  )
}

useGLTF.preload('/Assembly_for_robotic_car-transformed.glb')
